# Generated by Django 2.2.4 on 2019-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFood', '0002_auto_20190919_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='id_charge',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
