# Generated by Django 2.2.4 on 2019-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GFood', '0003_bill_id_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
